//! Session context — generates and displays rich project context on restore/startup.
//!
//! On `neuron restore`, this module:
//!   1. Reads the most recent conversation snapshot.
//!   2. Reads the manifest (name, language, last accessed).
//!   3. Reads current git branch + last commit.
//!   4. Writes `session_context.md` for human reference.
//!   5. Prints a rich terminal summary.

use anyhow::Result;
use chrono::Utc;
use colored::Colorize;
use sqlx;
use std::path::Path;
use tokio::fs;

use crate::git;
use crate::manifest::NeuronManifest;
use crate::search;
use crate::utils;

// ─── Write Initial Context ────────────────────────────────────────────────────

/// Write the initial `session_context.md` after `neuron init`.
pub async fn write_initial_context(project_root: &Path, manifest: &NeuronManifest) -> Result<()> {
    let context_path = project_root.join(".neuron").join("session_context.md");
    let now          = Utc::now().format("%Y-%m-%d %H:%M UTC").to_string();

    let content = format!(
        r#"# Neuron Session Context
**Project**: {} ({})
**Language**: {}
**Initialized**: {}
**Status**: 🟢 Active — Project just initialized

---

## Current Focus
Project freshly initialized. No files indexed yet.
Run `neuron watch` to begin real-time indexing.

## Open Decisions
- [ ] Confirm primary source directories to watch
- [ ] Set up `.neuronignore` if needed

## Last Git Branch
*(not yet detected — start `neuron watch` to activate git tracking)*

## Next Steps
1. Run `neuron watch` to start indexing
2. Make some commits — Neuron will track them
3. Run `neuron status` to see memory state
4. Run `neuron restore` after any directory change to reload context

---
*Auto-generated by Neuron session engine on init. Run `neuron restore` to reload.*
"#,
        manifest.name,
        manifest.id,
        manifest.language,
        now
    );

    fs::write(&context_path, content).await?;
    Ok(())
}

// ─── Print Status ─────────────────────────────────────────────────────────────

/// Print a compact status view for `neuron status`.
pub async fn print_status(project_root: &Path) -> Result<()> {
    let manifest = NeuronManifest::load(project_root).await?;
    let db_path  = utils::local_db_path(project_root);

    // Count indexed memory units
    let unit_count = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM memory_units")
            .fetch_one(&pool)
            .await
            .unwrap_or((0,));
        row.0
    } else {
        0
    };

    // Git info
    let git_info = git::current_branch(project_root)
        .unwrap_or_else(|_| "unknown".to_string());

    let last_accessed = {
        let dur = Utc::now().signed_duration_since(manifest.last_accessed);
        utils::format_duration(dur)
    };

    let bar = "─".repeat(50);
    println!("\n  {}", bar.dimmed());
    println!(
        "  {} {}  {}",
        "◉".bright_cyan().bold(),
        manifest.name.bold().white(),
        format!("({})", manifest.language).dimmed()
    );
    println!("  {}", bar.dimmed());
    println!("  {:20} {}", "Project ID:".dimmed(),      manifest.id.to_string().yellow());
    println!("  {:20} {}", "Root:".dimmed(),            project_root.display().to_string().cyan());
    println!("  {:20} {}", "Git Branch:".dimmed(),      git_info.bright_yellow());
    println!("  {:20} {}", "Memory Units:".dimmed(),    unit_count.to_string().green().bold());
    println!("  {:20} {}", "Last Accessed:".dimmed(),   last_accessed.white());
    println!("  {:20} {}", "Loop Guard:".dimmed(),      "Active ✓".green());
    println!("  {}\n", bar.dimmed());

    Ok(())
}

// ─── Print Restored Context ───────────────────────────────────────────────────

/// Print the full rich context on `neuron restore` or `neuron switch`.
/// Print the full rich context on `neuron restore` or `neuron switch`.
pub async fn print_restored_context(project_root: &Path, manifest: &NeuronManifest) -> Result<()> {
    let db_path = utils::local_db_path(project_root);

    // Count memory units
    let unit_count = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM memory_units")
            .fetch_one(&pool)
            .await
            .unwrap_or((0,));
        row.0
    } else {
        0
    };

    // Recent files touched
    let recent_files: Vec<String> = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let rows: Vec<(String,)> = sqlx::query_as(
            "SELECT DISTINCT path FROM memory_units WHERE unit_type = 'file' ORDER BY updated_at DESC LIMIT 8"
        )
        .fetch_all(&pool)
        .await
        .unwrap_or_default();
        rows.into_iter().map(|(p,)| p).collect()
    } else {
        vec![]
    };

    // Git info
    let git_branch = git::current_branch(project_root)
        .unwrap_or_else(|_| "unknown".to_string());
    let last_commit = git::last_commit_message(project_root)
        .unwrap_or_else(|_| "(no commits yet)".to_string());

    // Read last conversation snapshot if any
    let conv_dir  = project_root.join(".neuron").join("conversations");
    let last_conv = latest_snapshot_content(&conv_dir).await;

    // Regenerate the file
    let _ = regenerate_session_context(project_root, manifest).await?;

    // ── Terminal output ───────────────────────────────────────────────────────
    let banner = "═".repeat(60);
    println!("  {}", banner.bright_cyan());
    println!(
        "  {} Context Restored: {}",
        "◈".bright_cyan().bold(),
        manifest.name.bold().white()
    );
    println!("  {}", banner.bright_cyan());
    println!("  {:22} {}", "Project:".dimmed(),      manifest.name.bold().bright_white());
    println!("  {:22} {}", "Language:".dimmed(),     manifest.language.bright_yellow());
    println!("  {:22} {}", "Root:".dimmed(),         project_root.display().to_string().cyan());
    println!("  {:22} {}", "Git Branch:".dimmed(),   git_branch.bright_yellow());
    println!("  {:22} {}", "Last Commit:".dimmed(),  utils::truncate(&last_commit, 50).white());
    println!("  {:22} {}", "Memory Units:".dimmed(), unit_count.to_string().green().bold());
    println!("  {:22} {}", "Indexed Files:".dimmed(),recent_files.len().to_string().green());

    if !recent_files.is_empty() {
        println!("\n  {} Recent files:", "📂".cyan());
        for f in &recent_files {
            println!("     {} {}", "·".dimmed(), f.dimmed());
        }
    }

    if let Some(ref conv) = last_conv {
        println!("\n  {} Last snapshot preview:", "💬".cyan());
        // Print first 5 lines of the last snapshot
        for line in conv.lines().take(5) {
            println!("     {}", line.dimmed());
        }
    }

    println!("\n  {}", banner.bright_cyan());
    println!(
        "  {} Run {} to search memory, {} to watch files.\n",
        "ℹ".cyan(),
        "neuron search <query>".yellow(),
        "neuron watch".yellow()
    );

    Ok(())
}

/// Regenerate `session_context.md` file in `.neuron/`.
pub async fn regenerate_session_context(project_root: &Path, manifest: &NeuronManifest) -> Result<String> {
    let db_path = utils::local_db_path(project_root);

    // Count memory units
    let unit_count = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM memory_units")
            .fetch_one(&pool)
            .await
            .unwrap_or((0,));
        row.0
    } else {
        0
    };

    // Recent files touched
    let recent_files: Vec<String> = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let rows: Vec<(String,)> = sqlx::query_as(
            "SELECT DISTINCT path FROM memory_units WHERE unit_type = 'file' ORDER BY updated_at DESC LIMIT 8"
        )
        .fetch_all(&pool)
        .await
        .unwrap_or_default();
        rows.into_iter().map(|(p,)| p).collect()
    } else {
        vec![]
    };

    // Git info
    let git_branch = git::current_branch(project_root)
        .unwrap_or_else(|_| "unknown".to_string());
    let last_commit = git::last_commit_message(project_root)
        .unwrap_or_else(|_| "(no commits yet)".to_string());

    // Read last conversation snapshot if any
    let conv_dir  = project_root.join(".neuron").join("conversations");
    let last_conv = latest_snapshot_content(&conv_dir).await;

    // Write updated session_context.md
    let now = Utc::now().format("%Y-%m-%d %H:%M UTC").to_string();
    let context_content = build_context_md(
        manifest,
        &git_branch,
        &last_commit,
        unit_count,
        &recent_files,
        last_conv.as_deref(),
        &now,
    );
    let ctx_path = project_root.join(".neuron").join("session_context.md");
    fs::write(&ctx_path, &context_content).await?;

    Ok(context_content)
}

/// Print the rich, ready-to-paste agent context.
pub async fn print_agent_context(project_root: &Path) -> Result<()> {
    let manifest = NeuronManifest::load(project_root).await?;
    let context_content = regenerate_session_context(project_root, &manifest).await?;

    println!("\n{}", "=== COPY BELOW THIS LINE FOR YOUR AI AGENT ===".green().bold());
    println!("{context_content}");
    println!("{}\n", "=============================================".green().bold());

    Ok(())
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async fn latest_snapshot_content(conv_dir: &Path) -> Option<String> {
    if !conv_dir.exists() {
        return None;
    }
    let mut entries = fs::read_dir(conv_dir).await.ok()?;
    let mut files: Vec<std::path::PathBuf> = vec![];
    while let Ok(Some(e)) = entries.next_entry().await {
        files.push(e.path());
    }
    files.sort();
    let last = files.last()?;
    fs::read_to_string(last).await.ok()
}

fn build_context_md(
    manifest:     &NeuronManifest,
    git_branch:   &str,
    last_commit:  &str,
    unit_count:   i64,
    recent_files: &[String],
    last_conv:    Option<&str>,
    now:          &str,
) -> String {
    let files_md = if recent_files.is_empty() {
        "*(no files indexed yet)*".to_string()
    } else {
        recent_files
            .iter()
            .map(|f| format!("- `{f}`"))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let conv_md = last_conv
        .map(|c| format!("```\n{}\n```", &c[..c.len().min(500)]))
        .unwrap_or_else(|| "*(no snapshots yet)*".to_string());

    format!(
        r#"# Neuron Session Context
**Project**: {} ({})
**Language**: {}
**Restored**: {}
**Status**: 🟢 Active

---

## Identity
- **Project ID**: `{}`
- **Root**: `{}`
- **Memory Units**: {}

## Git State
- **Branch**: `{}`
- **Last Commit**: {}

## Recently Indexed Files
{}

## Last Conversation Snapshot
{}

## Next Steps
1. Review recent files for changes since last session
2. Run `neuron search <topic>` to locate prior decisions
3. Run `neuron watch` to resume real-time indexing

---
*Auto-generated by Neuron session engine. Run `neuron restore` to regenerate.*
"#,
        manifest.name,
        manifest.id,
        manifest.language,
        now,
        manifest.id,
        manifest.root_path.display(),
        unit_count,
        git_branch,
        last_commit,
        files_md,
        conv_md
    )
}

