//! Session context — generates and displays rich project context on restore/startup.
//!
//! On `neuron restore`, this module:
//!   1. Reads the most recent conversation snapshot.
//!   2. Reads the manifest (name, language, last accessed).
//!   3. Reads current git branch + last commit.
//!   4. Writes `session_context.md` for human reference.
//!   5. Prints a rich terminal summary.

use anyhow::Result;
use chrono::Utc;
use colored::Colorize;
use sqlx;
use std::path::Path;
use std::str::FromStr;
use tokio::fs;

use crate::git;
use crate::manifest::NeuronManifest;
use crate::search;
use crate::utils;

// ─── Write Initial Context ────────────────────────────────────────────────────

/// Write the initial `session_context.md` after `neuron init`.
pub async fn write_initial_context(project_root: &Path, manifest: &NeuronManifest) -> Result<()> {
    let context_path = project_root.join(".neuron").join("session_context.md");
    let now          = Utc::now().format("%Y-%m-%d %H:%M UTC").to_string();

    let content = format!(
        r#"# Neuron Session Context
**Project**: {} ({})
**Language**: {}
**Initialized**: {}
**Status**: 🟢 Active — Project just initialized

---

## Current Focus
Project freshly initialized. No files indexed yet.
Run `neuron watch` to begin real-time indexing.

## Open Decisions
- [ ] Confirm primary source directories to watch
- [ ] Set up `.neuronignore` if needed

## Last Git Branch
*(not yet detected — start `neuron watch` to activate git tracking)*

## Next Steps
1. Run `neuron watch` to start indexing
2. Make some commits — Neuron will track them
3. Run `neuron status` to see memory state
4. Run `neuron restore` after any directory change to reload context

---
*Auto-generated by Neuron session engine on init. Run `neuron restore` to reload.*
"#,
        manifest.name,
        manifest.id,
        manifest.language,
        now
    );

    fs::write(&context_path, content).await?;
    Ok(())
}

// ─── Print Status ─────────────────────────────────────────────────────────────

/// Print a compact status view for `neuron status`.
pub async fn print_status(project_root: &Path) -> Result<()> {
    let manifest = NeuronManifest::load(project_root).await?;
    let db_path  = utils::local_db_path(project_root);

    // Count indexed memory units
    let unit_count = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM memory_units")
            .fetch_one(&pool)
            .await
            .unwrap_or((0,));
        row.0
    } else {
        0
    };

    // Git info
    let git_info = git::current_branch(project_root)
        .unwrap_or_else(|_| "unknown".to_string());

    let last_accessed = {
        let dur = Utc::now().signed_duration_since(manifest.last_accessed);
        utils::format_duration(dur)
    };

    let bar = "─".repeat(50);
    println!("\n  {}", bar.dimmed());
    println!(
        "  {} {}  {}",
        "◉".bright_cyan().bold(),
        manifest.name.bold().white(),
        format!("({})", manifest.language).dimmed()
    );
    println!("  {}", bar.dimmed());
    println!("  {:20} {}", "Project ID:".dimmed(),      manifest.id.to_string().yellow());
    println!("  {:20} {}", "Root:".dimmed(),            project_root.display().to_string().cyan());
    println!("  {:20} {}", "Git Branch:".dimmed(),      git_info.bright_yellow());
    println!("  {:20} {}", "Memory Units:".dimmed(),    unit_count.to_string().green().bold());
    println!("  {:20} {}", "Last Accessed:".dimmed(),   last_accessed.white());
    println!("  {:20} {}", "Loop Guard:".dimmed(),      "Active ✓".green());
    println!("  {}\n", bar.dimmed());

    Ok(())
}

// ─── Print Restored Context ───────────────────────────────────────────────────

/// Print the full rich context on `neuron restore` or `neuron switch`.
/// Print the full rich context on `neuron restore` or `neuron switch`.
pub async fn print_restored_context(project_root: &Path, manifest: &NeuronManifest) -> Result<()> {
    let db_path = utils::local_db_path(project_root);

    // Count memory units
    let unit_count = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM memory_units")
            .fetch_one(&pool)
            .await
            .unwrap_or((0,));
        row.0
    } else {
        0
    };

    // Recent files touched
    let recent_files: Vec<String> = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let rows: Vec<(String,)> = sqlx::query_as(
            "SELECT DISTINCT path FROM memory_units WHERE unit_type = 'file' ORDER BY updated_at DESC LIMIT 8"
        )
        .fetch_all(&pool)
        .await
        .unwrap_or_default();
        rows.into_iter().map(|(p,)| p).collect()
    } else {
        vec![]
    };

    // Git info
    let git_branch = git::current_branch(project_root)
        .unwrap_or_else(|_| "unknown".to_string());
    let last_commit = git::last_commit_message(project_root)
        .unwrap_or_else(|_| "(no commits yet)".to_string());

    // Read last conversation snapshot if any
    let conv_dir  = project_root.join(".neuron").join("conversations");
    let last_conv = latest_snapshot_content(&conv_dir).await;

    // Regenerate the file
    let _ = regenerate_session_context(project_root, manifest).await?;

    // ── Terminal output ───────────────────────────────────────────────────────
    let banner = "═".repeat(60);
    println!("  {}", banner.bright_cyan());
    println!(
        "  {} Context Restored: {}",
        "◈".bright_cyan().bold(),
        manifest.name.bold().white()
    );
    println!("  {}", banner.bright_cyan());
    println!("  {:22} {}", "Project:".dimmed(),      manifest.name.bold().bright_white());
    println!("  {:22} {}", "Language:".dimmed(),     manifest.language.bright_yellow());
    println!("  {:22} {}", "Root:".dimmed(),         project_root.display().to_string().cyan());
    println!("  {:22} {}", "Git Branch:".dimmed(),   git_branch.bright_yellow());
    println!("  {:22} {}", "Last Commit:".dimmed(),  utils::truncate(&last_commit, 50).white());
    println!("  {:22} {}", "Memory Units:".dimmed(), unit_count.to_string().green().bold());
    println!("  {:22} {}", "Indexed Files:".dimmed(),recent_files.len().to_string().green());

    if !recent_files.is_empty() {
        println!("\n  {} Recent files:", "📂".cyan());
        for f in &recent_files {
            println!("     {} {}", "·".dimmed(), f.dimmed());
        }
    }

    if let Some(ref conv) = last_conv {
        println!("\n  {} Last snapshot preview:", "💬".cyan());
        // Print first 5 lines of the last snapshot
        for line in conv.lines().take(5) {
            println!("     {}", line.dimmed());
        }
    }

    println!("\n  {}", banner.bright_cyan());
    println!(
        "  {} Run {} to search memory, {} to watch files.\n",
        "ℹ".cyan(),
        "neuron search <query>".yellow(),
        "neuron watch".yellow()
    );

    Ok(())
}

/// Regenerate `session_context.md` file in `.neuron/`.
pub async fn regenerate_session_context(project_root: &Path, manifest: &NeuronManifest) -> Result<String> {
    let db_path = utils::local_db_path(project_root);

    // Count memory units
    let unit_count = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM memory_units")
            .fetch_one(&pool)
            .await
            .unwrap_or((0,));
        row.0
    } else {
        0
    };

    // Recent files touched
    let recent_files: Vec<String> = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let rows: Vec<(String,)> = sqlx::query_as(
            "SELECT DISTINCT file_path FROM memory_units WHERE unit_type = 'file' ORDER BY updated_at DESC LIMIT 8"
        )
        .fetch_all(&pool)
        .await
        .unwrap_or_default();
        rows.into_iter().map(|(p,)| p).collect()
    } else {
        vec![]
    };

    // Git info
    let git_branch = git::current_branch(project_root)
        .unwrap_or_else(|_| "unknown".to_string());
    let last_commit = git::last_commit_message(project_root)
        .unwrap_or_else(|_| "(no commits yet)".to_string());

    // Read last conversation snapshot if any
    let conv_dir  = project_root.join(".neuron").join("conversations");
    let last_conv = latest_snapshot_content(&conv_dir).await;

    // Write updated session_context.md
    let now = Utc::now().format("%Y-%m-%d %H:%M UTC").to_string();
    let context_content = build_context_md(
        manifest,
        &git_branch,
        &last_commit,
        unit_count,
        &recent_files,
        last_conv.as_deref(),
        &now,
    );
    let ctx_path = project_root.join(".neuron").join("session_context.md");
    fs::write(&ctx_path, &context_content).await?;

    Ok(context_content)
}

/// Get the NEURON ACTIVE WORKSPACE CONTEXT block as a String.
pub async fn get_agent_context_string(project_root: &Path, include: &[String]) -> Result<String> {
    let manifest = NeuronManifest::load(project_root).await?;
    let db_path  = utils::local_db_path(project_root);
    let git_branch = git::current_branch(project_root).unwrap_or_else(|_| "unknown".to_string());

    let config = crate::config::NeuronConfig::load(project_root).await;

    // Symbol count (exclude raw file units)
    let unit_count: i64 = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        sqlx::query_as("SELECT COUNT(*) FROM memory_units WHERE unit_type != 'file'")
            .fetch_one(&pool).await.unwrap_or((0,)).0
    } else { 0 };

    // Apply profile matrix parameters
    let (max_files, max_syms) = if config.profile == "antigravity" {
        (8, 6)
    } else if config.profile == "claude" {
        (5, 3)
    } else { // "openai"
        (3, 2)
    };

    // Top symbols per file
    let modules_md: String = if db_path.exists() {
        let pool = search::open_local_db(&db_path).await?;
        let query_files = format!(
            "SELECT DISTINCT file_path FROM memory_units WHERE unit_type != 'file' ORDER BY updated_at DESC LIMIT {}",
            max_files
        );
        let files: Vec<(String,)> = sqlx::query_as(&query_files)
            .fetch_all(&pool)
            .await
            .unwrap_or_default();
        let mut out = String::new();
        for (fp,) in files {
            out.push_str(&format!("\n### Module: `{}`\n", fp));
            
            // For openai profile, filter only Class or Module or high level symbols, or just limit count.
            let query_syms = if config.profile == "openai" {
                format!(
                    "SELECT symbol_name, symbol_type, semantic_intent FROM memory_units \
                     WHERE file_path = ?1 AND unit_type != 'file' AND symbol_type IN ('class', 'struct', 'module', 'enum') LIMIT {}",
                    max_syms
                )
            } else {
                format!(
                    "SELECT symbol_name, symbol_type, semantic_intent FROM memory_units \
                     WHERE file_path = ?1 AND unit_type != 'file' LIMIT {}",
                    max_syms
                )
            };

            let syms: Vec<(String, String, Option<String>)> = sqlx::query_as(&query_syms)
                .bind(&fp)
                .fetch_all(&pool)
                .await
                .unwrap_or_default();
            for (name, kind, intent) in syms {
                let d = intent.filter(|s| !s.is_empty()).unwrap_or_else(|| "—".into());
                out.push_str(&format!("*   `{}` ({}) - *Intent:* {}\n", name, kind, d));
            }
        }
        if out.is_empty() {
            "*(No symbols indexed yet — run `neuron watch` to index your codebase)*".to_string()
        } else { out }
    } else {
        "*(No symbols indexed yet — run `neuron watch` to index your codebase)*".to_string()
    };

    // Evolution ledger cap based on profile settings
    let ledger_cap = if config.profile == "antigravity" {
        50
    } else if config.profile == "claude" {
        5
    } else {
        0
    };

    let ledger_md: String = if manifest.evolution_ledger.is_empty() || ledger_cap == 0 {
        "*   No tweaks recorded yet — start `neuron watch` to begin tracking.".to_string()
    } else {
        manifest.evolution_ledger.iter().rev().take(ledger_cap).map(|e|
            format!("*   **{}** - *Tweak:* {} -> *Reason:* {}", e.timestamp, e.tweak, e.reason)
        ).collect::<Vec<_>>().join("\n")
    };

    // ── Cross-project synthesis ───────────────────────────────────────────────
    let mut cross_project_md = String::new();
    if !include.is_empty() {
        for alias in include {
            match crate::project_manager::resolve_alias(alias).await {
                Err(e) => {
                    cross_project_md.push_str(&format!(
                        "\n### ⚠ Alias `{}` not found: {}\n", alias, e
                    ));
                }
                Ok(ext_root) => {
                    let ext_db = utils::local_db_path(&ext_root);
                    if !ext_db.exists() {
                        cross_project_md.push_str(&format!(
                            "\n### `{}` — no index found (run `neuron power-up` on that workspace)\n",
                            alias
                        ));
                        continue;
                    }

                    let ext_pool = search::open_local_db(&ext_db).await?;

                    // Top 3 files × 3 symbols, high-level only
                    let ext_files: Vec<(String,)> = sqlx::query_as(
                        "SELECT DISTINCT file_path FROM memory_units \
                         WHERE unit_type != 'file' ORDER BY updated_at DESC LIMIT 3"
                    ).fetch_all(&ext_pool).await.unwrap_or_default();

                    cross_project_md.push_str(&format!(
                        "\n---\n## 🔗 Cross-Project: `{}`\n", alias
                    ));

                    for (fp,) in &ext_files {
                        cross_project_md.push_str(&format!("\n### Module: `{}`\n", fp));
                        let syms: Vec<(String, String, Option<String>)> = sqlx::query_as(
                            "SELECT symbol_name, symbol_type, semantic_intent FROM memory_units \
                             WHERE file_path = ?1 AND unit_type != 'file' LIMIT 3"
                        ).bind(fp).fetch_all(&ext_pool).await.unwrap_or_default();

                        for (name, kind, intent) in syms {
                            let raw_intent = intent.unwrap_or_default();
                            let clean = crate::sanitize::sanitize_content(&raw_intent);
                            let clean_name = crate::sanitize::sanitize_content(&name);
                            cross_project_md.push_str(&format!(
                                "*   `{}` ({}) - *Intent:* {}\n", clean_name, kind,
                                if clean.is_empty() { "—".to_string() } else { clean }
                            ));
                        }
                    }

                    // Last 2 ledger entries from the external manifest
                    if let Ok(ext_manifest) = crate::manifest::NeuronManifest::load(&ext_root).await {
                        if !ext_manifest.evolution_ledger.is_empty() {
                            cross_project_md.push_str("\n**Recent tweaks:**\n");
                            for e in ext_manifest.evolution_ledger.iter().rev().take(2) {
                                let clean_tweak = crate::sanitize::sanitize_content(&e.tweak);
                                cross_project_md.push_str(&format!(
                                    "*   **{}** - {}\n", e.timestamp, clean_tweak
                                ));
                            }
                        }
                    }

                    // Guard token cap
                    if cross_project_md.len() > config.token_cap / 4 {
                        cross_project_md.push_str("\n> *[Cross-project output truncated at token cap]*\n");
                        break;
                    }
                }
            }
        }
    }

    // ── Cascading parent mutation injection (automatic, no flag needed) ────────
    let mut parent_mutation_md = String::new();
    // Look up this project's ID from the global index
    if let Ok(current_project_id) = crate::dependency::project_id_for_alias(&manifest.name).await {
        if let Ok(parent_ids) = crate::dependency::get_parent_ids(&current_project_id).await {
            for parent_id in &parent_ids {
                // Get mutations within last 48 hours
                if let Ok(mutations) = crate::dependency::get_recent_mutations(parent_id, 48).await {
                    if !mutations.is_empty() {
                        // Resolve parent name
                        let parent_name = {
                            let db_path = utils::global_db_path().ok();
                            if let Some(db) = db_path {
                                if db.exists() {
                                    let opts = sqlx::sqlite::SqliteConnectOptions::from_str(
                                        &format!("sqlite://{}", db.display())
                                    ).ok();
                                    if let Some(o) = opts {
                                        if let Ok(p) = sqlx::SqlitePool::connect_with(o).await {
                                            let row: Option<(String,)> = sqlx::query_as(
                                                "SELECT name FROM projects WHERE id = ?1 LIMIT 1"
                                            ).bind(parent_id).fetch_optional(&p).await.unwrap_or(None);
                                            row.map(|(n,)| n).unwrap_or_else(|| parent_id.clone())
                                        } else { parent_id.clone() }
                                    } else { parent_id.clone() }
                                } else { parent_id.clone() }
                            } else { parent_id.clone() }
                        };

                        parent_mutation_md.push_str(&format!(
                            "\n---\n## ⚠️ Parent Interface Mutations: `{}`\n\
                             > *Detected within last 48 hours — review before building*\n\n",
                            parent_name
                        ));
                        for (sym_name, sym_type, changed_at) in &mutations {
                            parent_mutation_md.push_str(&format!(
                                "* `{}` ({}) — signature changed at `{}`\n",
                                sym_name, sym_type, &changed_at[..19]
                            ));
                        }
                    }
                }
            }
        }
    }

    let context_block = format!(
"# NEURON ACTIVE WORKSPACE CONTEXT
> **Project:** {} | **Branch:** `{}` | **Memory Units:** {}

## 🎯 TOP-LEVEL INTENT
{}

## 🛠️ RECENT ARCHITECTURAL TWEAKS (Last 3 Sessions)
{}

## 🧩 CRITICAL MODULES & SYMBOLS IN FOCUS
{}{}{}",
        manifest.name, git_branch, unit_count,
        manifest.top_level_intent,
        ledger_md,
        modules_md,
        cross_project_md,
        parent_mutation_md,
    );

    Ok(context_block)
}

/// Print the NEURON ACTIVE WORKSPACE CONTEXT block — optimised for AI agent pasting.
/// `export_path`: `None` = print to terminal, `Some("-")` = stdout only (pipe mode), `Some(path)` = write to file.
/// `include`: optional list of global project aliases whose top symbols are merged into the output.
pub async fn print_agent_context(project_root: &Path, export_path: Option<&str>, include: &[String]) -> Result<()> {
    let context_block = get_agent_context_string(project_root, include).await?;

    // Persist
    let ctx_path = project_root.join(".neuron").join("session_context.md");
    fs::write(&ctx_path, &context_block).await?;

    let delimited = format!(
        "<!-- NEURON_CONTEXT_START -->\n{}\n<!-- NEURON_CONTEXT_END -->",
        context_block
    );

    match export_path {
        Some("-") => {
            println!("{}", delimited);
        }
        Some(path) => {
            fs::write(path, &delimited).await?;
            println!(
                "\n{}  Context exported to {}\n",
                "✓".green().bold(),
                path.cyan()
            );
        }
        None => {
            println!("\n{}", "╔══════════════════════════════════════════════════════╗".bright_cyan());
            println!("{}",  "║      NEURON — COPY BELOW FOR YOUR AI AGENT          ║".bright_cyan().bold());
            println!("{}\n", "╚══════════════════════════════════════════════════════╝".bright_cyan());
            println!("{}", context_block);
            println!("\n{}\n", "══════════════════════════════════════════════════════".bright_cyan());
        }
    }

    Ok(())
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async fn latest_snapshot_content(conv_dir: &Path) -> Option<String> {
    if !conv_dir.exists() {
        return None;
    }
    let mut entries = fs::read_dir(conv_dir).await.ok()?;
    let mut files: Vec<std::path::PathBuf> = vec![];
    while let Ok(Some(e)) = entries.next_entry().await {
        files.push(e.path());
    }
    files.sort();
    let last = files.last()?;
    fs::read_to_string(last).await.ok()
}

fn build_context_md(
    manifest:     &NeuronManifest,
    git_branch:   &str,
    last_commit:  &str,
    unit_count:   i64,
    recent_files: &[String],
    last_conv:    Option<&str>,
    now:          &str,
) -> String {
    let files_md = if recent_files.is_empty() {
        "*(no files indexed yet)*".to_string()
    } else {
        recent_files
            .iter()
            .map(|f| format!("- `{f}`"))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let conv_md = last_conv
        .map(|c| format!("```\n{}\n```", &c[..c.len().min(500)]))
        .unwrap_or_else(|| "*(no snapshots yet)*".to_string());

    format!(
        "# Neuron Session Context\n\
**Project**: {name} ({id}) | **Language**: {lang} | **Branch**: `{branch}`\n\
**Memory Units**: {units} | **Restored**: {now}\n\
**Status**: 🟢 Active\n\n\
## Git State\n\
- **Last Commit**: {commit}\n\n\
## Recently Indexed Files\n{files}\n\n\
## Last Conversation Snapshot\n{conv}\n\n\
---\n\
*Auto-generated by Neuron v7. Run `neuron restore` to regenerate.*\n",
        name   = manifest.name,
        id     = manifest.id,
        lang   = manifest.language,
        branch = git_branch,
        units  = unit_count,
        now    = now,
        commit = last_commit,
        files  = files_md,
        conv   = conv_md,
    )
}

